apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: balance-transaction-hpa
  labels:
    app: balance-transaction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: balance-transaction
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50