apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # 使用base64编码后的值
  redis_host: {{ .Values.redis.host | b64enc | quote }}
  redis_port: {{ .Values.redis.port | b64enc | quote }}
  redis_password: {{ .Values.redis.password | b64enc | quote }}