apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbcs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rbcs.name" . }}
    helm.sh/chart: {{ include "rbcs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "rbcs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}