spring:
  application:
    name: rbcs
  datasource:
    url: ${DB_URL:jdbc:mysql://172.29.33.213:3306/rbcs}
    username: ${DB_USERNAME:rbcs}
    password: ${DB_PASSWORD:rbcs}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:172.29.33.213}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:Rbcs2025}
      database: 1
      timeout: 6000
      # 根据实际需求调整以下参数
      lettuce:
        pool:
          max-active: 100
          max-idle: 5
          min-idle: 0
          max-wait: -1ms
flyway:
  baseline-on-migrate: true
  locations: classpath:/db/migration

resilience4j:
  retry:
    instances:
      financialTransactionRetry:
        maxAttempts: 3 # 最大重试次数
        waitDuration: 500ms # 重试间隔
        enableExponentialBackoff: true # 是否启用指数退避策略
        exponentialBackoffMultiplier: 2 # 指数退避乘数
        ignoreExceptions: # 忽略这些异常，不进行重试
          - org.springframework.web.client.HttpClientErrorException
        retryExceptions: # 仅重试这些异常
          - org.springframework.web.client.ResourceAccessException
          - java.lang.RuntimeException
