replicaCount: 2

image:
  repository: crpi-u4kl0nx0bi63pklq.cn-hangzhou.personal.cr.aliyuncs.com/seanlau2019/rbcs
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

livenessProbe:
  httpGet:
    path: /balance/v1/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /balance/v1/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10


# 阿里云数据库RDS
mysql:
  enabled: true
  db_url: jdbc:mysql://rm-bp17fdf923e79c2y7.rwlb.rds.aliyuncs.com/rbcs
  db_username: "rbcs"
  db_password: "your-mysql-password"

# 阿里云Redis服务
redis:
  host: "r-bp1bzu0g9it6n5zg76.redis.rds.aliyuncs.com"
  port: "6379"
  password: "your-redis-password"
