replicaCount: 2

image:
  repository: crpi-u4kl0nx0bi63pklq.cn-hangzhou.personal.cr.aliyuncs.com/seanlau2019/rbcs
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

livenessProbe:
  httpGet:
    path: /balance/v1/transaction
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /balance/v1/transaction
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

secret:
  enabled: true
  username: "rbcs"
  password: "rbcs"

env:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_USERNAME:
    secretKeyRef:
      name: "{{ .Release.Name }}-db-secret"
      key: username
  DB_PASSWORD:
    secretKeyRef:
      name: "{{ .Release.Name }}-db-secret"
      key: password